spring.cloud.gateway.httpserver.wiretap: true
spring.cloud.gateway.httpclient.wiretap: true
logging.level.reactor.netty: debug
logging.level.com.example.httptrace.gw: debug
logging.level.reactor.netty.channel.FluxReceive: trace
logging.file.name: "${PWD:/opt}/log/application.log"
#logging.file.path: /opt/log
management.endpoints.web.exposure.include: '*'
